### ISSUE TITLE
support for grafana 8 or 9

### ISSUE THREAD

**Issue by 2327** [G-Core/cdn-stats-datasource-plugin#2]
I tried install plugin in grafana 8 and 9 with 1.0.8 and 1.0.11 versions of plugin. I see plugin in plugin list, but i cant find this datasource type in configuration/Data Sources. After i downgraded my gf to 7 and plugin is working.

I did not find supported versions in the documentation. Tell me if versions are supported grafana above 7?

Thanks.

**Comment by denisz** [comment]
@2327 
Hello,
Try the following one:

`docker run -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/G-Core/cdn-stats-datasource-plugin/releases/download/v1.0.11/gcorelabs-cdn-stats-datasource-1.0.11.zip;gcorelabs-cdn-stats-datasource" \
  -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=gcorelabs-cdn-stats-datasource" \
  grafana/grafana-enterprise:8.2.0`

You need to allow the unsigned gcorelabs-cdn-stats-datasource plugin.

**Comment by 2327** [comment]
Hello. Thank for  your answer.

That's exactly what I did. But two days ago new grafana has released and it works without any problems. Now i have grafana 9.0.3 with gcore and many other plugins. Thanks!
