### ISSUE TITLE
Grafana v11.2.0

### ISSUE THREAD

**Issue by AndrewOga** [G-Core/cdn-stats-datasource-plugin#8]
hello
help me install the plugin on Grafana v11.2.0
the plugin has been installed

In the plugin, I click "Add new data source", An empty data source page is created.
if I click "Explore data", an error comes out:
"gcorelabs-cdn-stats-datasource-3 plugin failed
Error: Error loading http://gra-grf1-lp1.hq.bc/core:plugin/gcorelabs-cdn-stats-datasource.js?_cache=1.0.14 (SystemJS Error#3 https://github.com/systemjs/systemjs/blob/main/docs/errors.md#3)"

**Comment by andreas-kokkalis** [comment]
@AndrewOga 
Just installed on Grafana 11.3.0

Set the following environment variables:
```
    GF_ALLOW_LOADING_UNSIGNED_PLUGINS = "gcorelabs-cdn-stats-datasource"
    GF_DEFAULT_APP_MODE               = "development"
```

Ensure plugin is on path `/var/lib/grafana/plugins/`

This worked for me.

**Comment by AndrewOga** [comment]
@andreas-kokkalis
Thanks!

**Comment by gotjoshua** [comment]
this helped me to get it loaded, but:
```
cdn-stats plugin failed
Error: 404 , loading https://grafana.tam.ma/public/plugins/gcorelabs-cdn-stats-datasource/module.js?_cache=1743454849734 (SystemJS Error#7 https://github.com/systemjs/systemjs/blob/main/docs/errors.md#7)
```

**Comment by gotjoshua** [comment]
this helped me to get it loaded, but 
```
cdn-stats plugin failed
Error: 404 , loading https://grafana.instance.com/public/plugins/gcorelabs-cdn-stats-datasource/module.js?_cache=1743454849734 (SystemJS Error#7 https://github.com/systemjs/systemjs/blob/main/docs/errors.md#7)
```
